### ISSUE TITLE
URSYS NetCall does not return correct data when undefined

### ISSUE THREAD

**Issue by daveseah** [dsriseah/ursys#30]
Refined semantics for `Endpoint.netCall('NET:MESSAGE',{})` are
1. to return `undefined` when there is no message handler anywhere
2. to return a single object response if there is only one handler
3. to return an array of object responses if there are multiple handlers
4. if a handler does NOT return data, then the response should return an empty object

**This is not working in the case of (4).**

Additionally, there is a bug in the original fix in commit 0259b311 which incorrectly chooses either `awaitHandlers()` or `awaitRemoteHandlers()`. It should be doing both and concatenating the results before running `NormalizeData()` on the return handlers.

**Comment by daveseah** [comment]
This will be resolved by PR of comment-module-3 branch

**Comment by dsriseah** [comment]
This is fixed in 1f498e0
